AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production

Resources:
  ServerlessBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref Prefix, !Ref Environment, "serverless" ] ]
  
Outputs:
  ServerlessBucket:
    Value: !Ref ServerlessBucket
    Export:
      Name: !Sub "${AWS::StackName}-ServerlessBucket"
